### ISSUE TITLE
MAC builds

### ISSUE THREAD

**Issue by phdsg** [phdsg/PvC#2]
until i have a machine that i can test the mac builds on, i'll post them here.
they're made in a vmware high sierra.
not sure if they work or not on a real mac.

**Comment by phdsg** [comment]
[PvC-0.5.3-mac.zip](https://github.com/phdsg/PvC/files/1545884/PvC-0.5.3-mac.zip)

**Comment by nay-seven** [comment]
ye, i can confirm too ( yosemite and El capitan), thanks !
 just need some caption for the comparator

**Comment by nay-seven** [comment]
and btw, i want to thank you for your vu meters, i use them to have a visual feedback from my MIDI CC ;-)
check this small video :[https://www.facebook.com/groups/vcvrack/permalink/141864369807049/?comment_id=141864713140348&notif_id=1513001264116611&notif_t=group_comment](url)

**Comment by nay-seven** [comment]
and if you like the idea, i have a small request : a thru output on this module would simplify the patching in this case ;-)

**Comment by phdsg** [comment]
wow, wasn't expecting anybody actually using it besides myself :)
as you may have noticed i'm just starting this whole programming trip.
the vumeter was my second module and it's really just a let's-try-and-see-if-this-works thing, ...so far.
my initial plan was to expand it at some point. have a bipolar mode, etc.
but i'm not there yet. programming wise.
the thru is easy tho. i can add that in the next release.

**Comment by nay-seven** [comment]
Cool ! good news and thank a lot !

**Comment by nay-seven** [comment]
I wanted to quote you in the FB post but I do not know your FB name ?

**Comment by phdsg** [comment]
ya, i actually can't stand facebook and quit a long time ago.
the account i use atm is an old one i used to get free-if-u-like-us promo vsts and stuff.
only reactivated for vcv. fbname is something like "phdsg gsdhp" i think

**Comment by nay-seven** [comment]
ok, so better will promote your github next release ;-)

**Comment by nay-seven** [comment]
hey, did'nt see you release a new one ! , thru works fine on Vu Bar ! thanks a lot !
