### ISSUE TITLE
comparator example failed to open

### ISSUE THREAD

**Issue by nay-seven** [phdsg/PvC#3]
i've this message when i try to open your vcv example for this module with last release on Mac

JSON parsing error at <stream> 7:1 '[' or '{' expected near '<'

**Comment by phdsg** [comment]
oh. thx 4 checking them out. could be that i saved them with the dev version of rack i was working with. i'll update them in the next few days and will test and save them with the official rack version.
sorry for the messup.

**Comment by phdsg** [comment]
btw, which one the vcv files? or both?

**Comment by nay-seven** [comment]
yes, both ;-)

**Comment by phdsg** [comment]
i uploaded a bunch again after i saved them in official rack v0.5. hope that does it.

**Comment by phdsg** [comment]
closing. (patches are currently not available anyway, but they'll be once i finished the migration of the docs)
