### ISSUE TITLE
Plugin Manager

### ISSUE THREAD

**Issue by Phal-anx** [phdsg/PvC#5]
Hi there!

I wanted to know if you could do zipped binaries (mac, win and lin).
Right now the plugin manager only have a link to your sources (therefor no +Free button) but not everyone is capable to compile it.

Greetings,
Michael

**Comment by phdsg** [comment]
can and will.
soon(ish).
it's on my todo list, but there are still some other things above that.

**Comment by Phal-anx** [comment]
nice to hear ;) 

all the best!

**Comment by phdsg** [comment]
ok, i think i figured it out...

just right in time with the plugin manager getting disabled.
