### ISSUE TITLE
Can't build any version of these plugins + the community json file is messed up

### ISSUE THREAD

**Issue by Chaircrusher** [phdsg/PvC#6]
Subject line says it all. Should this build against Rack v0.5.1?
-*- mode: compilation; default-directory: "/develop/vcv/Rack/plugins/PvC/" -*-
Compilation started at Thu Jan 11 13:51:21

make -k
g++ -O3 -std=c++11  -fPIC -I../../include -I../../dep/include -DVERSION=0.5.7 -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_LIN -c -o build/src/ShutIt.cpp.o src/ShutIt.cpp
src/ShutIt.cpp:46:7: error: ‘void ShutIt::reset()’ marked override, but does not override
  void reset() override {
       ^
src/ShutIt.cpp:52:7: error: ‘void ShutIt::randomize()’ marked override, but does not override
  void randomize() override {
       ^
make: *** [build/src/ShutIt.cpp.o] Error 1
g++ -O3 -std=c++11  -fPIC -I../../include -I../../dep/include -DVERSION=0.5.7 -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_LIN -c -o build/src/Oomph.cpp.o src/Oomph.cpp
src/Oomph.cpp:53:29: error: expected class-name before ‘{’ token
 struct PvCFader : SVGSlider {
                             ^
src/Oomph.cpp: In constructor ‘PvCFader::PvCFader()’:
src/Oomph.cpp:55:3: error: ‘maxHandlePos’ was not declared in this scope
   maxHandlePos = Vec(1, 1);
   ^
src/Oomph.cpp:56:3: error: ‘minHandlePos’ was not declared in this scope
   minHandlePos = Vec(1, 225);
   ^
src/Oomph.cpp:57:3: error: ‘background’ was not declared in this scope
   background->svg = SVG::load(assetPlugin(plugin, "res/components/PvCFader.svg"));
   ^
src/Oomph.cpp:59:3: error: ‘box’ was not declared in this scope
   box.size = background->box.size;
   ^
src/Oomph.cpp:60:3: error: ‘handle’ was not declared in this scope
   handle->svg = SVG::load(assetPlugin(plugin, "res/components/PvCFaderCap.svg"));
   ^
src/Oomph.cpp: In constructor ‘OomphWidget::OomphWidget()’:
src/Oomph.cpp:85:91: error: no matching function for call to ‘OomphWidget::addParam(PvCFader*)’
  addParam(createParam<PvCFader>(Vec(7, 22), module, Oomph::AMOUNT_PARAM, 0.0f, 1.0f, 0.0f));
                                                                                           ^
src/Oomph.cpp:85:91: note: candidate is:
In file included from ../../include/gui.hpp:2:0,
                 from ../../include/rack.hpp:8,
                 from src/pvc.hpp:1,
                 from src/Oomph.cpp:8:
../../include/app.hpp:44:7: note: void rack::ModuleWidget::addParam(rack::ParamWidget*)
  void addParam(ParamWidget *param);
       ^
../../include/app.hpp:44:7: note:   no known conversion for argument 1 from ‘PvCFader*’ to ‘rack::ParamWidget*’
In file included from src/pvc.hpp:1:0,
                 from src/Oomph.cpp:8:
../../include/rack.hpp: In instantiation of ‘TParamWidget* rack::createParam(rack::Vec, rack::Module*, int, float, float, float) [with TParamWidget = PvCFader]’:
src/Oomph.cpp:85:90:   required from here
../../include/rack.hpp:48:17: error: ‘struct PvCFader’ has no member named ‘box’
  param->box.pos = pos;
                 ^
../../include/rack.hpp:49:16: error: ‘struct PvCFader’ has no member named ‘module’
  param->module = module;
                ^
../../include/rack.hpp:50:17: error: ‘struct PvCFader’ has no member named ‘paramId’
  param->paramId = paramId;
                 ^
../../include/rack.hpp:51:2: error: ‘struct PvCFader’ has no member named ‘setLimits’
  param->setLimits(minValue, maxValue);
  ^
../../include/rack.hpp:52:2: error: ‘struct PvCFader’ has no member named ‘setDefaultValue’
  param->setDefaultValue(defaultValue);
  ^
make: *** [build/src/Oomph.cpp.o] Error 1
g++ -O3 -std=c++11  -fPIC -I../../include -I../../dep/include -DVERSION=0.5.7 -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_LIN -c -o build/src/Multy.cpp.o src/Multy.cpp
src/Multy.cpp:48:7: error: ‘void Multy::reset()’ marked override, but does not override
  void reset() override {
       ^
src/Multy.cpp:54:7: error: ‘void Multy::randomize()’ marked override, but does not override
  void randomize() override {
       ^
make: *** [build/src/Multy.cpp.o] Error 1
g++ -O3 -std=c++11  -fPIC -I../../include -I../../dep/include -DVERSION=0.5.7 -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_LIN -c -o build/src/Vubar.cpp.o src/Vubar.cpp
make: Target `all' not remade because of errors.

Compilation exited abnormally with code 2 at Thu Jan 11 13:51:23

**Comment by phdsg** [comment]
from the fader/slider error it looks like you are using rack master...
i'm using 0.5.
the override errors are just warnings on my system. will look into them.

**Comment by phdsg** [comment]
oh, also what's the error with the community json? yesterday was the first time i submitted and it passed all the tests.

**Comment by Chaircrusher** [comment]
The checkout doesn't work. I'm cleaning up a big mess I made with my build system, I will look again...
This line:   "source": "https://github.com/phdsg/PvC/tree/0.5.7",
That's a repo that doesn't work.

**Comment by phdsg** [comment]
oh, i see. can't clone the tag links. didn't know. will fix.

**Comment by phdsg** [comment]
i suspect the override errors are also related to api changes in rack-master over rack-v0.5. at least i can not reproduce them. not even warnings.

**Comment by Chaircrusher** [comment]
I think the override errors was PEBKAC -- Problem Exists Between Keyboard And Chair.

**Comment by phdsg** [comment]
reset(), randomize() etc. are changed in rack-master to onReset() onRandomize() etc.
